# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    name: '${{ matrix.os }}: build and test (docker: ${{ matrix.docker }})'
    strategy:
      matrix:
          os: [ubuntu-latest]
          docker: [false]
          include:
            - docker: true
              os: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
  
    - name: Run a one-line script
      run: |
        mkdir build
        touch build/file1
        touch build/file2
        
    - uses: actions/upload-artifact@v1
      with:
        name: build_${{ matrix.docker }}
        path: ${{github.workspace}}/build
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2.0
        with:
          path: ${{github.workspace}}/artifacts
      - name: find
        run: |
          find ${{github.workspace}}/artifacts
